Repository Railway-Op-Sim/railostools, pull requests merged in 2022-03, with the labels that each got.

#9 Moved to new artifact, added metadata package
  .github/workflows/rostools.yml
  java/pom.xml
  java/src/main/java/net/danielgill/railostools/metadata/Metadata.java
  java/src/main/java/net/danielgill/railostools/metadata/MetadataBuilder.java
  java/src/main/java/net/danielgill/railostools/railway/Railway.java
  java/src/test/java/net/danielgill/railostools/metadata/MetadataTest.java
  java/src/test/resources/Antwerpen_Centraal.toml
Labels: documentation, enhancement

#11 Switch to model based parser for TTB parsing in Python
  .github/workflows/rostools.yml
  .gitignore
  .sonarcloud.properties
  README.md
  python/README.md
  python/poetry.lock
  python/pyproject.toml
  python/pytest.ini
  python/railostools/__init__.py
  python/railostools/common/__init__.py
  python/railostools/common/coords.py
  python/railostools/common/enumeration.py
  python/railostools/exceptions.py
  python/railostools/metadata.py
  python/railostools/performance.py
  python/railostools/rly.py
  python/railostools/session.py
  python/railostools/ttb/__init__.py
  python/railostools/ttb/components/__init__.py
  python/railostools/ttb/components/actions.py
  python/railostools/ttb/components/finish.py
  python/railostools/ttb/components/start.py
  python/railostools/ttb/parsing/__init__.py
  python/railostools/ttb/parsing/actions.py
  python/railostools/ttb/parsing/components.py
  python/railostools/ttb/parsing/finish.py
  python/railostools/ttb/parsing/start.py
  python/railostools/ttb/string.py
  python/rostools/__init__.py
  python/rostools/discord.py
  python/rostools/exceptions.py
  python/rostools/metadata.py
  python/rostools/ttb.py
  python/tests/__init__.py
  python/tests/data/Antwerpen_Centraal.rly
  python/tests/data/Antwerpen_Centraal.toml
  python/tests/data/Birmingham_0700_Start.ttb
  python/tests/data/Log_Antwerpen_Centraal.txt
  python/tests/data/session.ini
  python/tests/test_data/Enoshima_Week_2021.ttb
  python/tests/test_metadata.py
  python/tests/test_parsing_ttb.py
  python/tests/test_perflog_monitor.py
  python/tests/test_rly_parsing.py
  python/tests/test_session.py
  python/tests/test_ttb.py
  python/tests/test_ttb_parsing.py
  python/tests/test_validation.py
Labels: enhancement

#12 Add handling of string based ID for service
  python/railostools/exceptions.py
  python/railostools/ttb/components/__init__.py
  python/railostools/ttb/parsing/__init__.py
  python/railostools/ttb/parsing/components.py
Labels: bug
